[qmae]
num_embeddings = 256
add_embeddings_per_step = 32
img_embedding_dim = 192
enc_embedding_dim = 192
enc_n_layers = 12
enc_n_heads = 4
dec_n_layers = 12
dec_n_heads = 4

# dataset
dataset = cifar10
image_size = 32
patch_size = 2

# quantisation
commitment_cost = 0.25
decay = 0.99

# loss
latent_consistency_sigma = 1
l1_loss_weight = 1
lpip_loss_weight = 1
vq_loss_weight = 1
latent_consistency_loss_weight = 1
# gan loss
discriminator_type = patch-gan
discriminator_weight = 0.8
gan_loss_epoch_start = 300
disc_num_layers = 3
disc_num_heads = 3
disc_in_channels = 3
disc_factor = 1
disc_use_actnorm = True
disc_ndf = 64
disc_loss = hinge

# training
accumulate_grad_batches = 2
batch_size = 256
max_epochs = 600
min_epochs = 300
num_epochs_schedule = warmup
learning_rate = 0.001
weight_decay = 0.05

[classifier]
# training
classifier_max_epochs = 100
classifier_min_epochs = 0
classifier_batch_size = 128


[sampling]
num_random_past_samples = 25000
num_random_past_samples_schedule = schedule
bootstrapped_dataset_path = /scratch/shared/beegfs/dzverev/artifacts
temperature = 1.23

[gpt]
gpt_num_layers = 12
gpt_num_epochs_max = 30
gpt_num_epochs_min = 30
gpt_batch_size = 128
gpt_accumulate_grad_batches = 1
gpt_learning_rate = 0.001
gpt_mask_ratio = 0.05
gpt_mask_token_weight = 0.95

[training]
accelerator = cuda
devices = auto
validate_every_n = 2
num_workers = 8
precision = 16-mixed
dataset_variance = 0.0632
dataset_path = /scratch/shared/beegfs/dzverev/datasets
best_model_prefix = /scratch/shared/beegfs/dzverev/artifacts
num_tasks = 5

[logging]
evaluation_logger = wandb
train_logger = wandb
logging_path = logs
checkpoint_path = /scratch/shared/beegfs/dzverev/artifacts