[qmae]
num_embeddings = 128
add_embeddings_per_step = 64
img_embedding_dim = 192
enc_embedding_dim = 192
enc_n_layers = 12
enc_n_heads = 3
dec_n_layers = 12
dec_n_heads = 3

# quantisation
commitment_cost = 0.25
decay = 0.99
# loss
latent_consistency_sigma = 1
l1_loss_weight = 1
lpip_loss_weight = 1
vq_loss_weight = 1
latent_consistency_loss_weight = 1
discriminator_weight = 0.8
gan_loss_disc_start = 6500
# training
accumulate_grad_batches = 1
batch_size = 128
max_epochs = 500
min_epochs = 500
num_epochs_schedule = fixed
learning_rate = 0.001
weight_decay = 0.05

[classifier]
# training
classifier_max_epochs = 100
classifier_min_epochs = 0
classifier_batch_size = 128


[sampling]
num_random_past_samples = 0
num_random_past_samples_schedule = fixed
bootstrapped_dataset_path = /scratch/shared/beegfs/dzverev/artifacts
temperature = 1.23

[gpt]
gpt_num_layers = 12
gpt_num_epochs_max = 15
gpt_num_epochs_min = 10
gpt_batch_size = 64
gpt_accumulate_grad_batches = 1
gpt_learning_rate = 0.001
gpt_mask_ratio = 0.05
gpt_mask_token_weight = 0.95

[training]
accelerator = cuda
devices = auto
validate_every_n = 2
num_workers = 8
precision = 32-true
dataset = cifar10
dataset_variance = 0.0632
dataset_path = /scratch/shared/beegfs/dzverev/datasets
best_model_prefix = /scratch/shared/beegfs/dzverev/artifacts
num_tasks = 5

[logging]
evaluation_logger = wandb
train_logger = wandb
logging_path = logs
checkpoint_path = /scratch/shared/beegfs/dzverev/artifacts